defaults:
  - _self_
  - ranker: ???
  - prediction_data: ???

ckpt_path: ???
name: ${ranker.model._target_}

data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  num_workers: 16
  shuffle: False

trainer:
  _target_: pytorch_lightning.Trainer
  deterministic: True
  precision: 16
  strategy: dp

hydra:
  job:
    chdir: True
